### PR TITLE
fix: refactor guess_layer_format() for more robustness

### LINKED ISSUE #157: Could guess_layer_format() use ows4r's `$getGeometryType()`?

### LINKED ISSUE #158: Problem with a layer of the physics server
@salvafern @bart-v is this a known problem?

The `"EMODnet:EP_PLATFORMS_MO_ATLAS"` layer seems somehow problematic.

``` r
wfs <- EMODnetWFS::emodnet_init_wfs_client(service = "physics")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> ✔ WFS client created successfully
#> ℹ Service: "https://prod-geoserver.emodnet-physics.eu/geoserver/ows"
#> ℹ Version: "2.0.0"
EMODnetWFS::emodnet_get_layer_info(wfs, layers = "EMODnet:EP_PLATFORMS_MO_ATLAS")
#> Error in `purrr::map_chr()`:
#> ℹ In index: 14.
#> Caused by error in `data.frame()`:
#> ! arguments imply differing number of rows: 1, 0
capabilities <- wfs$getCapabilities()
capabilities$getFeatureTypes()[[14]]$getName()
#> [1] "EMODnet:EP_PLATFORMS_MO_ATLAS"
capabilities$getFeatureTypes()[[14]]$getGeometryType()
#> NULL
capabilities$getFeatureTypes()[[14]]$getDescription(pretty = TRUE)
#> Error in data.frame(name = element$getName(), type = element$getType(), : arguments imply differing number of rows: 1, 0
```

<sup>Created on 2024-02-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by maelle**
Fix #158
Fix #157 

@salvafern could you please have a look?

``` r
wfs <- EMODnetWFS::emodnet_init_wfs_client(service = "physics")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> ✔ WFS client created successfully
#> ℹ Service: "https://prod-geoserver.emodnet-physics.eu/geoserver/ows"
#> ℹ Version: "2.0.0"
str(EMODnetWFS::emodnet_get_layer_info(wfs, layers = "EP_PLATFORMS_MO_ATLAS"))
#> rowws_df [1 × 9] (S3: rowwise_df/tbl_df/tbl/data.frame)
#>  $ data_source    : chr "emodnet_wfs"
#>  $ service_name   : chr "https://prod-geoserver.emodnet-physics.eu/geoserver/ows"
#>  $ service_url    : chr "physics"
#>  $ layer_name     : chr "EP_PLATFORMS_MO_ATLAS"
#>  $ title          : chr "EMODnet Physics - Moorings - ATLAS"
#>  $ abstract       : chr "EMODnet Physics DB of the mooring. Global collection. \r\nA mooring in oceanography is a collection of devices,"| __truncated__
#>  $ class          : chr "WFSFeatureType"
#>  $ format         : chr "data.frame"
#>  $ layer_namespace: chr "EMODnet"
#>  - attr(*, "groups")= tibble [1 × 1] (S3: tbl_df/tbl/data.frame)
#>   ..$ .rows: list<int> [1:1] 
#>   .. ..$ : int 1
#>   .. ..@ ptype: int(0)
```

<sup>Created on 2024-02-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/info.R [hunk 1]
```diff
@@ -117,7 +117,7 @@ get_abstract_null <- function(x) {
 }
 
 guess_layer_format <- function(layer) {
-  if (any(layer$getDescription(pretty = TRUE)[["geometry"]])) {
+  if (!is.null(layer$getGeometryType())) {
```
Comment (maelle) [inline R/info.R:120]: even with the fix in ows4R, this seems more logical to me

**Review by salvafern — APPROVED** [review]
